[package]
name = "aoc_2020_3_tobogan_traj"
version = "0.1.0"
authors = ["Ryan Boyer <ryanboyerpublic@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
